services:
  rauthy:
    # image: ghcr.io/moonlight8978/rauthy:latest
    build: .
    volumes:
      - rauthy-data:/app/data
      - rauthy-tls:/app/tls
    ports:
      - 8443:8443
    environment:
      LOCAL_TEST: "true"
      LOG_LEVEL: debug
      SWAGGER_UI_ENABLE: "true"
      SWAGGER_UI_PUBLIC: "true"

  mailcrab:
    image: marlonb/mailcrab:latest
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  rauthy-data:
  rauthy-tls:
